In [1]:
import numpy as np
import pandas as pd

In [2]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})
df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [3]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [4]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
#concat through column(by default axis=0)
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [6]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [7]:
#join two data frame
df3=pd.DataFrame({
    'name':['Alice','Bob','Charlic']
},index=[1,2,3])
df4=pd.DataFrame({
    'score':[85,90,75]
},index=[2,3,4])

In [8]:
df3

      name
1    Alice
2      Bob
3  Charlic

In [9]:
df4

   score
2     85
3     90
4     75

In [10]:
df3.join(df4)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlic   90.0

In [11]:
df3.join(df4,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlic   90.0
4      NaN   75.0

In [12]:
df4.join(df3)

   score     name
2     85      Bob
3     90  Charlic
4     75      NaN