In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})

In [3]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
df.shape

(5, 3)

In [5]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [7]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [8]:
df['A']+15

0    16
1    17
2    18
3    19
4    20
Name: A, dtype: int64

In [9]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

Applying Function

In [10]:
def square(x):
    return x**2

In [ ]:
#do not change in main data
df["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [12]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [14]:
#change of main data
df["B"]=df["B"].apply(square)

In [15]:
df

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [16]:
df["D"]=df["A"].apply(square)

In [17]:
df

   A     B    C   D
0  1   100  100   1
1  2   400  200   4
2  3   900  300   9
3  4  1600  400  16
4  5  2500  500  25

In [18]:
df["E"]=df["D"].apply(lambda x: x**3 + 4)

In [19]:
df

   A     B    C   D      E
0  1   100  100   1      5
1  2   400  200   4     68
2  3   900  300   9    733
3  4  1600  400  16   4100
4  5  2500  500  25  15629