In [1]:
import numpy as np
import pandas as pd

In [2]:
data={
    'Name':['priyansu','rahul','aman','arun'],
    'Age':[20,21,22,23],
    'City':['New Delhi','Gorakhpur','Goa','Mumbai'],
    'Salary':[5400,2400,7600,8700]
}
df=pd.DataFrame(data)
df

       Name  Age       City  Salary
0  priyansu   20  New Delhi    5400
1     rahul   21  Gorakhpur    2400
2      aman   22        Goa    7600
3      arun   23     Mumbai    8700

In [5]:
#which people which age is greater than 21
df[df["Age"]>21]

   Name  Age    City  Salary
2  aman   22     Goa    7600
3  arun   23  Mumbai    8700

In [8]:
#i only want people whose age is above 21 and their city must be mumbai
df[(df["Age"]>21) & (df["City"]=='Mumbai')]

   Name  Age    City  Salary
3  arun   23  Mumbai    8700