In [29]:
import numpy as np
import pandas as pd

In [30]:
data_list1=[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
df2=pd.DataFrame(data_list1)
col=['Name','Age','City','Salary']
df2=pd.DataFrame(data_list1,columns=col)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
#Create column
df2["Designation"]=["Doctor","Engg.","Doctor","Engg."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000       Engg.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Engg.

In [32]:
#Remove column
df2.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000       Engg.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Engg.

In [34]:
df2.drop('Designation',axis=1,inplace=True)

In [35]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
#MUltiple column remove
df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [40]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000