In [1]:
import numpy as np
import pandas as pd

In [3]:
data_list={
    'Name':['priyansu','rahul','aman','arun'],
    'Age':[20,21,22,23],
    'City':['New Delhi','Gorakhpur','Goa','Mumbai'],
    'Salary':[5400,2400,7600,8700]
}
df=pd.DataFrame(data_list)
df

       Name  Age       City  Salary
0  priyansu   20  New Delhi    5400
1     rahul   21  Gorakhpur    2400
2      aman   22        Goa    7600
3      arun   23     Mumbai    8700

In [ ]:
#select location of rows
#df[0] generate error
df.loc[[0,1]]

       Name  Age       City  Salary
0  priyansu   20  New Delhi    5400
1     rahul   21  Gorakhpur    2400

In [7]:
df.iloc[3]

Name        arun
Age           23
City      Mumbai
Salary      8700
Name: 3, dtype: object

In [12]:
#selecting subset of Rows and column
df.loc[[0,1]][["City","Salary"]]

        City  Salary
0  New Delhi    5400
1  Gorakhpur    2400

In [14]:
df.loc[[0,1]][["Age","Salary"]]

   Age  Salary
0   20    5400
1   21    2400